apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-deployment
  labels:
    app: kali-rolling
spec:
  replicas: 8
  selector:
    matchLabels:
      app: kali-rolling
  template:
    metadata:
      labels:
        app: kali-rolling
    spec:
      containers:
      - name: kalilinux/kali-rolling
        image: kalilinux/kali-rolling:latest
        ports:
        - containerPort: 8004
