apiVersion: apps/v1
kind: Deployment
metadata:
  name: openProject-deployment
  labels:
    app: community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
      - name: community
        image: openproject/community:latest
        ports:
        - containerPort: 8007
